###
https://localhost:3002/user/scheduleApiCall

###
https://localhost:3002/user/disableJS

###
https://localhost:3002/user/backForwardFakeGeolocation


###
https://localhost:3002/user/disableJS

###
https://localhost:3002/user/disableJS

###
https://localhost:3002/user/disableJS

###
https://localhost:3002/user/disableJS


