# Use a base image with Ubuntu
FROM ubuntu:latest

# Install necessary packages
RUN apt-get update \
    && apt-get install -y \
       nodejs \
       npm \
       python3 \
       python3-pip \
       g++ \
       sudo \
       ttyd

# Set the working directory to root '/'
WORKDIR /


# Clean up unnecessary files
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/*



#  docker build -t controlia:latest -f Dockerfile.controlia .